import { DEFAULT_GAS_PRICE, GrouplessKeyType } from '@alephium/web3'

export const NUM_OF_ZEROS_IN_QUINTILLION = 18

export const MINIMAL_GAS_AMOUNT = 20000
export const MAXIMAL_GAS_AMOUNT = 5000000
export const MINIMAL_GAS_PRICE = BigInt(100000000000) // 100 nanoALPH for the first year to prevent DoS attacks
export const MAXIMAL_GAS_FEE = DEFAULT_GAS_PRICE * BigInt(MAXIMAL_GAS_AMOUNT)

export const GENESIS_TIMESTAMP = 1231006505000

export enum WALLETCONNECT_ERRORS {
  TRANSACTION_SEND_FAILED = -32000,
  PARSING_SESSION_REQUEST_FAILED = -33000,
  TRANSACTION_BUILD_FAILED = -34000,
  TRANSACTION_SIGN_FAILED = -35000,
  MESSAGE_SIGN_FAILED = -36000,
  SIGNER_ADDRESS_DOESNT_EXIST = -37000,
  TRANSACTION_DECODE_FAILED = -38000
}

export const ONE_MINUTE_MS = 1000 * 60

export const FIVE_MINUTES_MS = 5 * ONE_MINUTE_MS

export const ONE_HOUR_MS = 60 * ONE_MINUTE_MS

export const ONE_DAY_MS = 24 * ONE_HOUR_MS

export const TRANSACTIONS_PAGE_DEFAULT_LIMIT = 20

export const FREQUENT_ADDRESSES_TRANSACTIONS_REFRESH_INTERVAL = ONE_MINUTE_MS
export const INFREQUENT_ADDRESSES_TRANSACTIONS_REFRESH_INTERVAL = FIVE_MINUTES_MS
export const PRICES_REFRESH_INTERVAL = FIVE_MINUTES_MS

export const GROUPLESS_ADDRESS_KEY_TYPE = 'gl-secp256k1' as GrouplessKeyType
