name: CI

on:
  push:
    branches: [master]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1

      - name: 🏗 Setup monorepo
        uses: ./.github/actions/setup-monorepo

      - name: Lint all workspaces
        run: pnpm run lint

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1

      - name: 🏗 Setup monorepo
        uses: ./.github/actions/setup-monorepo

      - name: Check that TypeScript compiles in all workspaces
        run: pnpm run typecheck

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1

      - name: 🏗 Setup monorepo
        uses: ./.github/actions/setup-monorepo

      - name: Run tests in all workspaces
        run: pnpm run test

  audit:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1

      - name: 🏗 Setup monorepo
        uses: ./.github/actions/setup-monorepo

      - name: Audit NPM dependencies
        run: pnpm audit --prod

  build-desktop-wallet:
    needs: [typecheck]
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1

      - name: 🏗 Setup monorepo
        uses: ./.github/actions/setup-monorepo

      - name: Extract platform name
        id: get-os
        run: echo "os=$(echo ${{ matrix.os }} | cut -d- -f1)" >> $GITHUB_OUTPUT
        shell: bash

      - name: Skip desktop wallet signing
        uses: jaywcjlove/github-action-package@6fb8b5f918c1cb2eb3e0416d5b9f45cd4af6ed16 # v2.0.0
        with:
          path: apps/desktop-wallet/package.json
          unset: build.win.sign

      - name: Building desktop wallet on ${{ steps.get-os.outputs.os }}
        run: cd apps/desktop-wallet && pnpm run ci:build:electron:${{ steps.get-os.outputs.os }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
