# Simple workflow for deploying static content to GitHub Pages
name: Deploy explorer to GH Pages

on:
  workflow_dispatch:

env:
  VITE_BACKEND_URL: https://backend.testnet.alephium.org
  VITE_NODE_URL: https://node.testnet.alephium.org
  VITE_NETWORK_TYPE: testnet

# Sets the GITHUB_TOKEN permissions to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  deploy-explorer-gh-pages:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: 🏗 Setup monorepo
        uses: ./.github/actions/setup-monorepo

      - name: Build
        run: cd apps/explorer && pnpm run ci:build:gh-pages

      - name: Set up Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload dist repository
          path: './apps/explorer/build'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
