name: Build and publish explorer docker image

on:
  workflow_dispatch:
  push:
    tags: ['@alephium/explorer@[0-9]+.[0-9]+.[0-9]+*']

jobs:
  buildx_and_publish_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.workflow_run.head_branch }}

      - name: 🏗 Setup monorepo
        uses: ./.github/actions/setup-monorepo

      - name: Build the static website
        run: cd apps/explorer && pnpm run ci:build

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Get the version
        id: get_version
        uses: martinbeentjes/npm-get-version-action@v1.3.1
        with:
          path: apps/explorer

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and publish docker image
        uses: docker/build-push-action@v2
        with:
          context: ./apps/explorer
          file: ./apps/explorer/docker/Dockerfile
          platforms: linux/amd64,linux/arm64
          tags: |
            docker.io/alephium/explorer:${{ steps.get_version.outputs.current-version }}
            docker.io/alephium/explorer:latest
          push: true
