name: Build and publish explorer docker image

on:
  workflow_dispatch:
  push:
    tags: ['@alephium/explorer@[0-9]+.[0-9]+.[0-9]+*']

jobs:
  buildx_and_publish_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
        with:
          fetch-depth: 0
          ref: ${{ github.event.workflow_run.head_branch }}

      - name: 🏗 Setup monorepo
        uses: ./.github/actions/setup-monorepo

      - name: Build the static website
        run: cd apps/explorer && pnpm run ci:build

      - name: Set up QEMU
        uses: docker/setup-qemu-action@c7c53464625b32c7a7e944ae62b3e17d2b600130 # v3.7.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1

      - name: Get the version
        id: get_version
        uses: martinbeentjes/npm-get-version-action@3cf273023a0dda27efcd3164bdfb51908dd46a5b # v1.3.1
        with:
          path: apps/explorer

      - name: Log in to Docker Hub
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and publish docker image
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        with:
          context: ./apps/explorer
          file: ./apps/explorer/docker/Dockerfile
          platforms: linux/amd64,linux/arm64
          tags: |
            docker.io/alephium/explorer:${{ steps.get_version.outputs.current-version }}
            docker.io/alephium/explorer:latest
          push: true
