name: Setup Monorepo
description: Prepare and install everything for the monorepo

inputs:
  node-version:
    description: Version of Node to use
    default: 20.18.0

  pnpm-version:
    description: Version of pnpm to use
    default: 9.4.0

  eas-version:
    description: Version of EAS CLI to use
    default: 16.18.0

  expo-token:
    description: Expo token to authenticate with
    required: false

runs:
  using: composite
  steps:
    - name: 🏗 Setup pnpm
      uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
      with:
        version: ${{ inputs.pnpm-version }}

    - name: 🏗 Setup Node
      uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
      with:
        node-version: ${{ inputs.node-version }}
        cache: pnpm

    - name: 🏗 Setup Expo
      if: ${{ inputs.expo-token }}
      uses: expo/expo-github-action@c7b66a9c327a43a8fa7c0158e7f30d6040d2481e # 8.2.1
      with:
        eas-version: ${{ inputs.eas-version }}
        token: ${{ inputs.expo-token }}

    - name: 📦 Install dependencies
      run: pnpm install --frozen-lockfile
      shell: bash

    - name: ♻️ Restore cache
      uses: actions/cache@9255dc7a253b0ccc959486e2bca901246202afeb # v5.0.1
      with:
        key: turbo-${{ runner.os }}-${{ github.sha }}
        restore-keys: |
          turbo-${{ runner.os }}
        path: |
          node_modules/.cache/turbo
          apps/*/.turbo
          packages/*/.turbo
